#![doc = include_str!("../README.md")]

// src/lib.rs

// 1. Export runtime modules
// The code generated by the macro refers to `syn_grammar::rt`.
// Therefore, this module must be publicly available.
pub mod rt {
    pub use super::token_filter;
    pub use grammar_kit::*;
}

/// Utilities for testing parsers.
pub use grammar_kit::testing;

pub trait SynTestExt<O> {
    fn parse_test(self, input: &str) -> testing::TestResult<O, syn::Error>;
}

impl<F, O> SynTestExt<O> for F
where
    F: FnOnce(syn::parse::ParseStream) -> syn::Result<O>,
    O: std::fmt::Debug,
{
    fn parse_test(self, input: &str) -> testing::TestResult<O, syn::Error> {
        let parser = |input: syn::parse::ParseStream| self(input);
        match syn::parse::Parser::parse_str(parser, input) {
            Ok(val) => testing::TestResult::new(Ok(val)).with_source(input),
            Err(e) => testing::TestResult::new(Err(e)).with_source(input),
        }
    }
}

// 3. Re-export the macro
// This allows the user to write: `use syn_grammar::grammar;`
pub use syn_grammar_macros::grammar;

#[doc(hidden)]
pub mod builtins;
pub mod token_filter;

// Export portable types
pub mod types {
    pub use syn_grammar_model::model::types::*;
}
pub use types::{Identifier, StringLiteral};
