//! Utilities for testing parsers generated by `syn-grammar`.
//!
//! This module provides a fluent API for testing parsing results,
//! asserting success/failure, and checking error messages.

use std::fmt::{Debug, Display};

// Helper for custom error formatting
type ErrorFormatter<E> = Box<dyn Fn(&E, Option<&str>) -> String>;

// A wrapper around Result to write fluent tests.
// Keeps ownership of the result to allow chaining assertions.
pub struct TestResult<T, E> {
    inner: Result<T, E>,
    context: Option<String>,
    source: Option<String>,
    formatter: Option<ErrorFormatter<E>>,
}

impl<T: Debug, E: Display + Debug> TestResult<T, E> {
    pub fn new(result: Result<T, E>) -> Self {
        Self {
            inner: result,
            context: None,
            source: None,
            formatter: None,
        }
    }

    /// Adds context description to the test result for better failure messages.
    pub fn with_context(mut self, context: &str) -> Self {
        self.context = Some(context.to_string());
        self
    }

    /// Adds the source code string to the test result for pretty printing errors.
    pub fn with_source(mut self, source: &str) -> Self {
        self.source = Some(source.to_string());
        self
    }

    /// Adds a custom error formatter.
    pub fn with_formatter<F>(mut self, formatter: F) -> Self
    where
        F: Fn(&E, Option<&str>) -> String + 'static,
    {
        self.formatter = Some(Box::new(formatter));
        self
    }

    fn format_context(&self) -> String {
        self.context
            .as_ref()
            .map(|c| format!("\nContext:  {}", c))
            .unwrap_or_default()
    }

    fn format_err(&self, err: &E) -> String {
        if let Some(formatter) = &self.formatter {
            formatter(err, self.source.as_deref())
        } else {
            format!("{}", err)
        }
    }

    /// Prints the result to stdout for debugging purposes.
    /// Useful when running tests with `-- --nocapture`.
    pub fn inspect(self) -> Self {
        let ctx = self.format_context();
        match &self.inner {
            Ok(val) => {
                println!("\n🔎 INSPECT SUCCESS: {}\nValue: {:?}\n", ctx, val);
            }
            Err(e) => {
                let msg = self.format_err(e);
                println!(
                    "\n🔎 INSPECT FAILURE: {}\nMessage: {}\nDebug:   {:?}\n",
                    ctx, msg, e
                );
            }
        }
        self
    }

    // =========================================================================
    // Success Assertions
    // =========================================================================

    /// 1. Asserts success and returns the value.
    ///    Terminates the chain for `TestResult` but allows inspecting the value `T`.
    pub fn assert_success(self) -> T {
        let ctx = self.format_context();
        match self.inner {
            Ok(val) => {
                println!("ℹ️  Asserting success.\n   Actual:   {:?}", val);
                val
            }
            Err(ref e) => {
                let msg = self.format_err(e);
                panic!(
                    "\n🔴 TEST FAILED (Expected Success, but got Error):{}\nMessage:  {}\nError Debug: {:?}\n", 
                    ctx, msg, e
                );
            }
        }
    }

    /// 2. Asserts success AND checks the value directly against an expected value.
    pub fn assert_success_is<Exp>(self, expected: Exp) -> T
    where
        T: PartialEq<Exp>,
        Exp: Debug,
    {
        let ctx = self.format_context();
        let val = self.assert_success();

        println!("ℹ️  Checking equality.\n   Expected: {:?}", expected);

        if val != expected {
            panic!(
                "\n🔴 TEST FAILED (Value Mismatch):{}\nExpected: {:?}\nGot:      {:?}\n",
                ctx, expected, val
            );
        }
        val
    }

    /// 3. Asserts success AND checks the value using a closure.
    pub fn assert_success_with<F>(self, f: F) -> T
    where
        F: FnOnce(&T),
    {
        let val = self.assert_success();
        println!("ℹ️  Asserting success with closure.");
        f(&val);
        val
    }

    /// 4. Asserts success AND checks the Debug representation matches.
    ///    Useful for types where PartialEq is hard to implement (e.g. syn types with Spans).
    pub fn assert_success_debug(self, expected_debug: &str) -> T {
        let ctx = self.format_context();
        let val = self.assert_success();
        let actual_debug = format!("{:?}", val);

        println!(
            "ℹ️  Checking debug representation.\n   Expected: {:?}",
            expected_debug
        );

        if actual_debug != expected_debug {
            panic!(
                "\n🔴 TEST FAILED (Debug Mismatch):{}\nExpected: {:?}\nGot:      {:?}\n",
                ctx, expected_debug, actual_debug
            );
        }
        val
    }

    /// 7. Asserts success AND checks if the string representation contains a specific substring.
    pub fn assert_success_contains(self, expected_part: &str) -> T
    where
        T: Display,
    {
        let ctx = self.format_context();
        let val = self.assert_success();
        let val_str = val.to_string();

        println!(
            "ℹ️  Checking success string contains {:?}.\n   Actual string: {:?}",
            expected_part, val_str
        );

        if !val_str.contains(expected_part) {
            panic!(
                "\n🔴 TEST FAILED (Content Mismatch):{}\nExpected to contain: {:?}\nGot:                 {:?}\n",
                ctx, expected_part, val_str
            );
        }
        val
    }

    // =========================================================================
    // Failure Assertions
    // =========================================================================

    /// 5. Asserts failure and returns the error `E`.
    ///    Terminates the chain so you can manually inspect the error object.
    pub fn assert_failure(self) -> E {
        let ctx = self.format_context();
        match self.inner {
            Ok(val) => {
                panic!(
                    "\n🔴 TEST FAILED (Expected Failure, but got Success):{}\nParsed Value: {:?}\n",
                    ctx, val
                );
            }
            Err(e) => {
                println!("ℹ️  Asserting failure.\n   Error:    {:?}", e);
                e
            }
        }
    }

    /// 6. Asserts failure AND checks if the message contains a specific text.
    ///    Returns `Self` to allow chaining multiple assertions on the same error.
    pub fn assert_failure_contains(self, expected_msg_part: &str) -> Self {
        let ctx = self.format_context();

        match &self.inner {
            Ok(val) => {
                panic!(
                    "\n🔴 TEST FAILED (Expected Failure, but got Success):{}\nParsed Value: {:?}\n",
                    ctx, val
                );
            }
            Err(err) => {
                let actual_msg = err.to_string();
                println!(
                    "ℹ️  Checking error message contains {:?}.\n   Actual message: {:?}",
                    expected_msg_part, actual_msg
                );

                if !actual_msg.contains(expected_msg_part) {
                    let formatted = self.format_err(err);
                    panic!(
                        "\n🔴 TEST FAILED (Error Message Mismatch):{}\nExpected part: {:?}\nActual msg:    {:?}\nError Debug:   {:?}\nFormatted:   \n{}\n", 
                        ctx, expected_msg_part, actual_msg, err, formatted
                    );
                }
            }
        }
        self
    }

    /// 8. Asserts failure AND checks if the message DOES NOT contain a specific text.
    ///    Returns `Self` to allow chaining.
    pub fn assert_failure_not_contains(self, unexpected_part: &str) -> Self {
        let ctx = self.format_context();

        match &self.inner {
            Ok(val) => {
                panic!(
                    "\n🔴 TEST FAILED (Expected Failure, but got Success):{}\nParsed Value: {:?}\n",
                    ctx, val
                );
            }
            Err(err) => {
                let actual_msg = err.to_string();
                println!(
                    "ℹ️  Checking error message NOT contains {:?}.\n   Actual message: {:?}",
                    unexpected_part, actual_msg
                );

                if actual_msg.contains(unexpected_part) {
                    let formatted = self.format_err(err);
                    panic!(
                        "\n🔴 TEST FAILED (Unexpected Error Message Content):{}\nUnexpected part: {:?}\nActual msg:      {:?}\nError Debug:     {:?}\nFormatted:\n{}\n", 
                        ctx, unexpected_part, actual_msg, err, formatted
                    );
                }
            }
        }
        self
    }

    // --- Deprecated Aliases ---

    #[deprecated(
        note = "this method should not be used, if you see this warning this indicates corruption of the test by ai hallucinations"
    )]
    pub fn assert_is_err(self) -> E {
        self.assert_failure()
    }

    #[deprecated(
        note = "this method should not be used, if you see this warning this indicates corruption of the test by ai hallucinations"
    )]
    pub fn get_success_value(self) -> T {
        self.assert_success()
    }

    #[deprecated(
        note = "this method should not be used, if you see this warning this indicates corruption of the test by ai hallucinations"
    )]
    pub fn assert_error_contains(self, _code: usize, expected_msg_part: &str) {
        self.assert_failure_contains(expected_msg_part);
    }
}

pub trait Testable<T, E> {
    fn test(self) -> TestResult<T, E>;
}

impl<T: Debug, E: Display + Debug> Testable<T, E> for Result<T, E> {
    fn test(self) -> TestResult<T, E> {
        TestResult::new(self)
    }
}
