//! Utilities for testing parsers generated by `syn-grammar`.
//!
//! This module provides a fluent API for testing parsing results,
//! asserting success/failure, and checking error messages.

use std::fmt::{Debug, Display};

type ErrorFormatter<E> = Box<dyn Fn(&E, Option<&str>) -> String>;

pub struct TestResult<T, E, S = ()> {
    pub inner: Result<T, E>,
    pub state: Option<S>,
    pub context: Option<String>,
    pub source: Option<String>,
    pub formatter: Option<ErrorFormatter<E>>,
}

// Der Extension-Trait, um `.test()` auf jedes Result aufzurufen.
pub trait Testable<T, E> {
    fn test(self) -> TestResult<T, E>;
}

impl<T, E: Display + Debug> Testable<T, E> for Result<T, E> {
    fn test(self) -> TestResult<T, E> {
        TestResult::new(self)
    }
}

impl<T: Debug, E: Display + Debug, S> TestResult<T, E, S> {
    pub fn new(result: Result<T, E>) -> Self {
        Self {
            inner: result,
            state: None,
            context: None,
            source: None,
            formatter: None,
        }
    }

    pub fn with_state(mut self, state: S) -> Self { self.state = Some(state); self }
    pub fn with_context(mut self, context: &str) -> Self { self.context = Some(context.to_string()); self }
    pub fn with_source(mut self, source: &str) -> Self { self.source = Some(source.to_string()); self }

    pub fn with_formatter<F>(mut self, formatter: F) -> Self
    where F: Fn(&E, Option<&str>) -> String + 'static,
    {
        self.formatter = Some(Box::new(formatter));
        self
    }

    pub fn format_context(&self) -> String {
        self.context.as_ref().map(|c| format!("\nContext:  {}", c)).unwrap_or_default()
    }

    pub fn format_err(&self, err: &E) -> String {
        if let Some(formatter) = &self.formatter {
            formatter(err, self.source.as_deref())
        } else {
            format!("{}", err)
        }
    }

    pub fn inspect(self) -> Self {
        let ctx = self.format_context();
        match &self.inner {
            Ok(val) => println!("\n🔎 INSPECT SUCCESS: {}\nValue: {:?}\n", ctx, val),
            Err(e) => {
                let msg = self.format_err(e);
                println!("\n🔎 INSPECT FAILURE: {}\nMessage: {}\nDebug:   {:?}\n", ctx, msg, e);
            }
        }
        self
    }

    pub fn assert_success(self) -> T {
        let ctx = self.format_context();
        match self.inner {
            Ok(val) => val,
            Err(ref e) => {
                let msg = self.format_err(e);
                panic!("\n🔴 TEST FAILED (Expected Success, but got Error):{}\n\nError Message:\n{}\n\nError Debug:\n{:?}\n", ctx, msg, e);
            }
        }
    }

    pub fn assert_success_is<Exp>(self, expected: Exp) -> T where T: PartialEq<Exp>, Exp: Debug, {
        let ctx = self.format_context();
        let val = self.assert_success();
        if val != expected {
            panic!("\n🔴 TEST FAILED (Value Mismatch):{}\nExpected: {:?}\nGot:      {:?}\n", ctx, expected, val);
        }
        val
    }

    pub fn assert_success_with<F>(mut self, f: F) -> T where F: FnOnce(&T, &S), S: Debug, {
        let state = self.state.take();
        let val = self.assert_success();
        let state_ref = state.as_ref().expect("State must be provided to use assert_success_with");
        f(&val, state_ref);
        val
    }

    pub fn assert_success_debug(self, expected_debug: &str) -> T {
        let ctx = self.format_context();
        let val = self.assert_success();
        let actual_debug = format!("{:?}", val);
        if actual_debug != expected_debug {
            panic!("\n🔴 TEST FAILED (Debug Mismatch):{}\nExpected: {:?}\nGot:      {:?}\n", ctx, expected_debug, actual_debug);
        }
        val
    }

    pub fn assert_success_contains(self, expected_part: &str) -> T where T: Display, {
        let ctx = self.format_context();
        let val = self.assert_success();
        let val_str = val.to_string();
        if !val_str.contains(expected_part) {
            panic!("\n🔴 TEST FAILED (Content Mismatch):{}\nExpected to contain: {:?}\nGot:                 {:?}\n", ctx, expected_part, val_str);
        }
        val
    }

    pub fn assert_failure(self) -> E {
        let ctx = self.format_context();
        match self.inner {
            Ok(val) => panic!("\n🔴 TEST FAILED (Expected Failure, but got Success):{}\nParsed Value: {:?}\n", ctx, val),
            Err(e) => e,
        }
    }

    pub fn assert_failure_contains(self, expected_msg_part: &str) -> Self {
        let ctx = self.format_context();
        match &self.inner {
            Ok(val) => panic!("\n🔴 TEST FAILED (Expected Failure, but got Success):{}\nParsed Value: {:?}\n", ctx, val),
            Err(err) => {
                let actual_msg = err.to_string();
                if !actual_msg.contains(expected_msg_part) {
                    let formatted = self.format_err(err);
                    panic!("\n🔴 TEST FAILED (Error Message Mismatch):{}\nExpected part: {:?}\nActual msg:    {:?}\n\nError Debug:\n{:?}\n\nFormatted:\n{}\n", ctx, expected_msg_part, actual_msg, err, formatted);
                }
            }
        }
        self
    }

    #[deprecated(note = "This method should not be used, if you see this warning this indicates corruption of the test by ai hallucinations")]
    pub fn assert_error_contains(self, _code: usize, expected_msg_part: &str) {
        self.assert_failure_contains(expected_msg_part);
    }
}

// Special assertions for float types
impl<E: Display + Debug, S> TestResult<f64, E, S> {
    pub fn assert_success_approx(self, expected: f64) -> f64 {
        let ctx = self.format_context();
        let val = self.assert_success();
        if (val - expected).abs() > f64::EPSILON {
            panic!("\n🔴 TEST FAILED (Approximate Value Mismatch):{}\nExpected: {:?}\nGot:      {:?}\nDiff:     {:?}\n", ctx, expected, val, (val - expected).abs());
        }
        val
    }
}

impl<E: Display + Debug, S> TestResult<f32, E, S> {
    pub fn assert_success_approx(self, expected: f32) -> f32 {
        let ctx = self.format_context();
        let val = self.assert_success();
        if (val - expected).abs() > f32::EPSILON {
            panic!("\n🔴 TEST FAILED (Approximate Value Mismatch):{}\nExpected: {:?}\nGot:      {:?}\nDiff:     {:?}\n", ctx, expected, val, (val - expected).abs());
        }
        val
    }
}
