// CXX Parser Library
// Contains the AST struct definitions and the grammar for parsing CXX FFI bridges.

use syn::{self, Attribute, Ident, LitStr, Macro};
use syn::parse::{Parse, ParseStream, Result};
use syn_grammar::grammar;

// 1. AST Node Definitions
#[derive(Debug)]
pub struct FfiMod {
    pub attrs: Vec<Attribute>,
    pub name: Ident,
    pub blocks: Vec<ExternBlock>,
}

#[derive(Debug)]
pub struct ExternBlock {
    pub is_unsafe: bool,
    pub lang: LitStr,
    pub items: Vec<CxxItem>,
}

#[derive(Debug)]
pub enum CxxItem {
    Type(Vec<Attribute>, Ident, syn::Generics),
    Function(Vec<Attribute>, Ident, syn::Generics, Vec<CxxArg>, syn::ReturnType),
    Macro(Macro),
}

#[derive(Debug)]
pub struct CxxArg {
    pub name: Ident,
    pub ty: syn::Type,
}

// 2. Grammar Definition
grammar! {
    grammar CxxParser {
        pub top_level_mod -> FfiMod =
            attrs:outer_attrs
            "mod" name:ident
            { blocks:extern_block* }
            -> {
                FfiMod { attrs, name: name.into(), blocks }
            }

        extern_block -> ExternBlock =
            is_unsafe:"unsafe"?
            "extern" lang:lit_str
            { items:cxx_item* }
            -> {
                ExternBlock {
                    is_unsafe: is_unsafe.is_some(),
                    lang: lang.into(),
                    items,
                }
            }

        cxx_item -> CxxItem =
            attrs:outer_attrs "type" name:ident generics:syn::Generics? ";" -> {
                CxxItem::Type(attrs, name.into(), generics.unwrap_or_default())
            }
          | attrs:outer_attrs "fn" name:ident generics:syn::Generics?
            paren(args:cxx_arg_list? ","?)
            ret:syn::ReturnType ";" -> {
                CxxItem::Function(attrs, name.into(), generics.unwrap_or_default(), args.unwrap_or_default(), ret)
            }
          | mac:syn::Macro ";" -> {
                CxxItem::Macro(mac)
            }

        cxx_arg_list -> Vec<CxxArg> = items:separated(cxx_arg, ",") -> { items }

        cxx_arg -> CxxArg =
            name:any_ident ":" ty:syn::Type -> {
                CxxArg { name: name.into(), ty }
            }
    }
}

// 3. Implement `Parse` for the root AST node.
impl Parse for FfiMod {
    fn parse(input: ParseStream) -> Result<Self> {
        // Delegate to the parser function generated by `syn-grammar`.
        CxxParser::parse_top_level_mod(input)
    }
}

// 4. Integration Tests
#[cfg(test)]
mod tests {
    use super::*;
    use quote::quote;
    use syn::parse2;

    #[test]
    fn parse_complex_cxx_bridge() {
        let input_tokens = quote! {
            #[cxx::bridge(namespace = "engine::internal")]
            mod ffi {
                unsafe extern "C++" {
                    include!("engine/core/events.h");
                    
                    type EventPayload<'b>;
                    type DispatchReceipt;

                    #[namespace = "engine::callbacks"]
                    fn dispatch_event_with_callback<'a, 'b>(
                        self: Pin<&mut EventDispatcher>,
                        payload: &'a mut CxxVector<EventPayload<'b>>,
                        filter: fn(&CxxString, Option<&[u8]>) -> bool,
                    ) -> Result<UniquePtr<DispatchReceipt>>;
                }
            }
        };

        let parsed_mod: FfiMod = parse2(input_tokens)
            .expect("Parser failed to process the TokenStream");

        // Assertions
        assert_eq!(parsed_mod.name.to_string(), "ffi");
        assert_eq!(parsed_mod.attrs.len(), 1);
        assert_eq!(parsed_mod.blocks.len(), 1);
        
        let extern_block = &parsed_mod.blocks[0];
        assert!(extern_block.is_unsafe);
        assert_eq!(extern_block.lang.value(), "C++");
        assert_eq!(extern_block.items.len(), 4);

        // Check the `include!` macro
        match &extern_block.items[0] {
            CxxItem::Macro(m) => assert_eq!(m.path.get_ident().unwrap().to_string(), "include"),
            _ => panic!("Expected a macro item at index 0"),
        }

        // Check the type with generics
        match &extern_block.items[1] {
            CxxItem::Type(_, name, generics) => {
                assert_eq!(name.to_string(), "EventPayload");
                assert!(!generics.params.is_empty());
            }
            _ => panic!("Expected a type item at index 1"),
        }

        // Check the type without generics
        match &extern_block.items[2] {
            CxxItem::Type(_, name, generics) => {
                assert_eq!(name.to_string(), "DispatchReceipt");
                assert!(generics.params.is_empty());
            }
            _ => panic!("Expected a type item at index 2"),
        }

        let function_item = match &extern_block.items[3] {
            CxxItem::Function(a, n, g, args, r) => Some((a, n, g, args, r)),
            _ => None
        }.expect("Expected a function item at index 3");

        let (_attrs, _name, generics, args, ret) = function_item;

        assert_eq!(args.len(), 3);
        assert_eq!(args[2].name.to_string(), "filter");
        assert!(generics.params.iter().any(|p| match p { syn::GenericParam::Lifetime(_) => true, _ => false}));

        let filter_type = &args[2].ty;
        let filter_type_string = quote!(#filter_type).to_string();
        let expected_filter_type = "fn ( & CxxString , Option < & [u8] > ) -> bool";
        assert_eq!(filter_type_string.replace(" ", ""), expected_filter_type.replace(" ", ""));

        let ret_type = &ret;
        let ret_type_string = quote!(#ret_type).to_string();
        assert!(ret_type_string.contains("Result"));
    }
}
