#![doc = include_str!("../README.md")]

// src/lib.rs

// 1. Export runtime modules
// The code generated by the macro refers to `syn_grammar::rt`.
// Therefore, this module must be publicly available.
#[doc(hidden)]
pub mod rt;

/// Utilities for testing parsers.
pub mod testing;

// 3. Re-export the macro
// This allows the user to write: `use syn_grammar::grammar;`
pub use syn_grammar_macros::grammar;

#[doc(hidden)]
pub use syn_grammar_macros::include_grammar;
